version: '3.9'
networks:
  inception:
    name: inception   
services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx/
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress/
    restart: always
    
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/afaris/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/afaris/data/mariadb
      o: bind